[package]
name = "rrt"
version = "0.1.0"
authors = ["Takashi Ogura <t.ogura@gmail.com>"]
description = "Path finding using dual-RRT connect"
license = "Apache-2.0"
keywords = ["search", "path-finding", "rrt", "robotics"]
categories = ["Algorithms"]
repository = "https://github.com/OTL/rrt"
documentation = "http://docs.rs/rrt"

[dependencies]
kdtree = "0.3.1"
rand = "0.3.15"
log = "0.3.8"
env_logger = "0.4.3"
#clippy = { version = "*", optional = true }

[features]
default = []

[dev-dependencies]
approx   = "*"
alga     = "*"
nalgebra = "*"
ncollide = "*"
kiss3d = "*"
